//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T2TiERP.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("T2TiERP.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         #region MetodoClient que estende a classe ???ServiceReference
        ///
        ///        [SearchWindowDataSource(typeof([NomeTabela]DTO))]
        ///        public new List&lt;[NomeTabela]DTO&gt; select[NomeTabela]([NomeTabela]DTO dtoPesquisa)
        ///        {
        ///            return base.select[NomeTabela](dtoPesquisa);
        ///        }
        ///
        ///		#Metodo de pesquisa SearchWindow
        ///        public void pesquisar[NomeTabela]()
        ///        {
        ///            try
        ///            {
        ///                SearchWindowApp searchWindow = new SearchWindowApp(typeof([NomeTabel [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CodigoAuxiliar {
            get {
                return ResourceManager.GetString("CodigoAuxiliar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;[NamespaceCliente].[NomeTabela]&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///             mc:Ignorable=&quot;d&quot; 
        ///d:DesignHeight=&quot;500&quot; d:DesignWidth=&quot;700&quot;&gt;
        ///    &lt;DockPanel LastChildFill=&quot;True&quot;&gt;
        ///        &lt;StackPanel DockPanel.Do [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTO_xaml {
            get {
                return ResourceManager.GetString("DTO_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace [NamespaceCliente]
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for [NomeTabela].xaml
        ///    /// &lt;/summary&gt;
        ///    public partial class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTO_xaml_cs {
            get {
                return ResourceManager.GetString("DTO_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;.[NomeTabela]&quot; xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; mc:Ignorable=&quot;d&quot; d:DesignHeight=&quot;500&quot; d:DesignWidth=&quot;700&quot;&gt;
        ///	&lt;DockPanel LastChildFill=&quot;True&quot;&gt;
        ///		&lt;StackPanel DockPanel.Dock=&quot;Top&quot; HorizontalAlignment=&quot;Right&quot; Orientation=&quot;Horizontal&quot;&gt;
        ///			&lt;Button Name=&quot;btGravar&quot; Width=&quot;100 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalhe_xaml {
            get {
                return ResourceManager.GetString("DTODetalhe_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace 
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for Detalhe.xaml
        ///    /// &lt;/summary&gt;
        ///    public partial class [NomeTabela] : UserCon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalhe_xaml_cs {
            get {
                return ResourceManager.GetString("DTODetalhe_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;.[NomeTabela]Lista&quot; 
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///             mc:Ignorable=&quot;d&quot; xmlns:sys=&quot;clr-namespace:System;assembly=mscorlib&quot; 
        ///             xmlns:util=&quot;clr-namespace:.Util&quot; 
        ///             xmlns:exp=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalheLista_xaml {
            get {
                return ResourceManager.GetString("DTODetalheLista_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///using ExportarParaArquivo.Control;
        ///
        ///namespace 
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for DetalheLista.xaml
        ///	/// 
        ///	/// The MIT Licens [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalheLista_xaml_cs {
            get {
                return ResourceManager.GetString("DTODetalheLista_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;.[NomeTabela]Principal&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///             xmlns:view=&quot;clr-namespace:.View&quot;
        ///             mc:Ignorable=&quot;d&quot; 
        ///             d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;700&quot;&gt;
        ///    &lt;TabControl&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalhePrincipal_xaml {
            get {
                return ResourceManager.GetString("DTODetalhePrincipal_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace ]
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for DetalhePrincipal.xaml
        ///    /// &lt;/summary&gt;
        ///    public partial class [NomeTabela] [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTODetalhePrincipal_xaml_cs {
            get {
                return ResourceManager.GetString("DTODetalhePrincipal_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;[NamespaceCliente].[NomeTabela]Lista&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///             mc:Ignorable=&quot;d&quot; 
        ///             xmlns:sys=&quot;clr-namespace:System;assembly=mscorlib&quot;
        ///             xmlns:util=&quot;clr-namespace:[Nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTOLista_xaml {
            get {
                return ResourceManager.GetString("DTOLista_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace [NamespaceCliente]
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for [NomeTabela].xaml
        ///	/// 
        ///	/// The MIT License
        ///	///
        ///	/// Copy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTOLista_xaml_cs {
            get {
                return ResourceManager.GetString("DTOLista_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;UserControl x:Class=&quot;[NamespaceCliente].[NomeTabela]Principal&quot;
        ///             xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///             xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///             xmlns:mc=&quot;http://schemas.openxmlformats.org/markup-compatibility/2006&quot; 
        ///             xmlns:d=&quot;http://schemas.microsoft.com/expression/blend/2008&quot; 
        ///             xmlns:view=&quot;clr-namespace:&quot;
        ///             mc:Ignorable=&quot;d&quot; 
        ///             d:DesignHeight=&quot;300&quot; d:DesignWidth=&quot;700&quot;&gt;
        ///    &lt;T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTOPrincipal_xaml {
            get {
                return ResourceManager.GetString("DTOPrincipal_xaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Windows;
        ///using System.Windows.Controls;
        ///using System.Windows.Data;
        ///using System.Windows.Documents;
        ///using System.Windows.Input;
        ///using System.Windows.Media;
        ///using System.Windows.Media.Imaging;
        ///using System.Windows.Navigation;
        ///using System.Windows.Shapes;
        ///
        ///namespace [NamespaceCliente]
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Interaction logic for [NomeTabela]Principal.xaml
        ///    /// &lt;/summary&gt;
        ///    public part [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTOPrincipal_xaml_cs {
            get {
                return ResourceManager.GetString("DTOPrincipal_xaml_cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Collections.ObjectModel;
        ///using System.Windows.Input;
        ///
        ///namespace [NamespaceCliente]
        ///{
        ///	/// 
        ///	/// The MIT License
        ///	///
        ///	/// Copyright: Copyright (C) 2010 T2Ti.COM
        ///	///
        ///	/// Permission is hereby granted, free of charge, to any person
        ///	/// obtaining a copy of this software and associated documentation
        ///	/// files (the &quot;Software&quot;), to deal in the Software without
        ///	/// restriction, including without  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DTOViewModel {
            get {
                return ResourceManager.GetString("DTOViewModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 		
        ///		private void btPesquisa[NomeReferencia]_Click(object sender, RoutedEventArgs e)
        ///        {
        ///            try
        ///            {
        ///                (([NomeTabela]ViewModel)DataContext).pesquisar[NomeReferencia]();
        ///            }
        ///            catch (Exception ex)
        ///            {
        ///                MessageBox.Show(ex.Message, &quot;Alerta do sistema&quot;);
        ///            }
        ///        }
        ///.
        /// </summary>
        internal static string EventosView {
            get {
                return ResourceManager.GetString("EventosView", resourceCulture);
            }
        }
    }
}
